### ISSUE TITLE
Error in section 2 MVVM

### ISSUE THREAD

**Issue by cas8180** [jamesmontemagno/xamarin.forms-workshop#2]
Downloaded source, tried everything to run lesson 2 MVVM. 

- Rebuilt solution
-Deleted obj folder
-Cleaned solution.
-Restarted VS

cant get passed this error
![image](https://user-images.githubusercontent.com/1483688/68817393-6c1c0e00-0636-11ea-968d-71b9bad6ff37.png)

Great into to Xamarin Forms! Its good that news experience this pitfalls early on so they can be prepared for what working with this framework is really like.

**Comment by jamesmontemagno** [comment]
Looks like you are having an issue perhaps with the build... Perhaps it is a long name violation, can you move it to a shorter directory such as "C:/Workshop"
